
train_test_split:
  src_dir: "/c/py/predictive_esp/src/data/train_test_split.py"
  CLI_params: "/c/py/predictive_esp/data/interim/renamed /c/py/predictive_esp/data/interim/train_test 3"


train_dag:
  resample_data:
    src_dir: "/c/py/predictive_esp/src/data/resample_data.py"
    CLI_params: "/c/py/predictive_esp/data/interim/train_test/train /c/py/predictive_esp/data/interim/resampled/train \"01-01-2021\" \"30-09-2021\""

  merge_by_well:
    src_dir: "/c/py/predictive_esp/src/data/merge_by_well.py"
    CLI_params: "/c/py/predictive_esp/data/interim/resampled/train /c/py/predictive_esp/data/interim/merged_wells/train \"01-01-2021\" \"30-09-2021\""

  join_events:
    src_dir: "/c/py/predictive_esp/src/features/join_events.py"
    CLI_params: "/c/py/predictive_esp/data/interim/merged_wells/train /c/py/predictive_esp/data/raw/events /c/py/predictive_esp/data/interim/joined_events/train"

  expand_target:
    src_dir: "/c/py/predictive_esp/src/features/expand_target.py"
    CLI_params: "/c/py/predictive_esp/data/interim/joined_events/train /c/py/predictive_esp/data/interim/expanded_target/train 7"

  build_features:
    src_dir: "/c/py/predictive_esp/src/features/build_features_v2.py"
    # input_path events_path output_path target_window verbose
    CLI_params: "/c/py/predictive_esp/data/interim/merged_wells/train /c/py/predictive_esp/data/interim/featured/train"

  merge:
    src_dir: "/c/py/predictive_esp/src/data/merge_features.py"
    CLI_params: "/c/py/predictive_esp/data/interim/featured/train /c/py/predictive_esp/data/interim/expanded_target/train /c/py/predictive_esp/data/interim/merged_features/train"

  create_dataset:
    src_dir: "/c/py/predictive_esp/src/data/create_dataset.py"
    # input_path output_path
    CLI_params: "/c/py/predictive_esp/data/interim/merged_features/train /c/py/predictive_esp/data/interim/datasets/train.csv"

  clear_nulls:
    src_dir: "/c/py/predictive_esp/src/data/preprocessing.py"
    CLI_params: "/c/py/predictive_esp/data/interim/datasets/train.csv /c/py/predictive_esp/data/processed/train.csv"


predict_dag:
  resample_data:
    src_dir: "/c/py/predictive_esp/src/data/resample_data.py"
    CLI_params: "/c/py/predictive_esp/data/interim/train_test/test /c/py/predictive_esp/data/interim/resampled/test \"01-10-2021\" \"31-12-2021\""

  merge_by_well:
    src_dir: "/c/py/predictive_esp/src/data/merge_by_well.py"
    CLI_params: "/c/py/predictive_esp/data/interim/resampled/test /c/py/predictive_esp/data/interim/merged_wells/test \"01-10-2021\" \"31-12-2021\""

  join_events:
    src_dir: "/c/py/predictive_esp/src/features/join_events.py"
    CLI_params: "/c/py/predictive_esp/data/interim/merged_wells/test /c/py/predictive_esp/data/raw/events /c/py/predictive_esp/data/interim/joined_events/test"

  expand_target:
    src_dir: "/c/py/predictive_esp/src/features/expand_target.py"
    CLI_params: "/c/py/predictive_esp/data/interim/joined_events/test /c/py/predictive_esp/data/interim/expanded_target/test 7"

  build_features:
    src_dir: "/c/py/predictive_esp/src/features/build_features_v2.py"
    # input_path events_path output_path target_window verbose
    CLI_params: "/c/py/predictive_esp/data/interim/merged_wells/test /c/py/predictive_esp/data/interim/featured/test"

  merge:
    src_dir: "/c/py/predictive_esp/src/data/merge_features.py"
    CLI_params: "/c/py/predictive_esp/data/interim/featured/test /c/py/predictive_esp/data/interim/expanded_target/test /c/py/predictive_esp/data/interim/merged_features/test"

  create_dataset:
    src_dir: "/c/py/predictive_esp/src/data/create_dataset.py"
    # input_path output_path
    CLI_params: "/c/py/predictive_esp/data/interim/merged_features/test /c/py/predictive_esp/data/interim/datasets/test.csv"

  clear_nulls:
    src_dir: "/c/py/predictive_esp/src/data/preprocessing.py"
    CLI_params: "/c/py/predictive_esp/data/interim/datasets/test.csv /c/py/predictive_esp/data/processed/test.csv"


predict:
  src_dir: "/c/py/predictive_esp/src/models/predict.py"
  # input_path output_path model_name
  CLI_params: "/c/py/predictive_esp/data/processed/test.csv /c/py/predictive_esp/data/predictions lr_model.pkl"


train:
  src_dir: "/c/py/predictive_esp/src/models/train.py"
  # train_path output_path target_name model_name
  CLI_params: "/c/py/predictive_esp/data/processed/train.csv /c/py/predictive_esp/models/lr_model.pkl \"target_failure\""


evaluate:
  src_dir: "/c/py/predictive_esp/src/models/evaluate.py"
  CLI_params: "/c/py/predictive_esp/models/lr_model.pkl /c/py/predictive_esp/data/processed/test.csv \"target_failure\" /c/py/predictive_esp/data/predictions"

