create_dataset:
  columns: ['time', 'active_power', 'active_power2', 'electricity_gage',
       'frequency', 'intake_pressure', 'line_pressure', 'liquid_rate',
       'motor_load', 'motor_temperature', 'op_current1', 'op_current2',
       'op_current3', 'pump_temperature', 'voltageAB', 'voltageBC',
       'voltageCA', 'well_id']
  src_dir: "/c/py/predictive_esp/src/data/create_dataset.py"
  # input_path output_path
  CLI_params: "/c/py/predictive_esp/data/interim/featured /c/py/predictive_esp/data/processed"

build_features:
  src_dir: "/c/py/predictive_esp/src/features/build_features.py"
  # input_path events_path output_path target_window verbose
  CLI_params: "/c/py/predictive_esp/data/interim/joined /c/py/predictive_esp/data/raw/events /c/py/predictive_esp/data/interim/featured 7 False"

resample_data:
  begin_time: "01-01-2021"
  end_time: "31-12-2021"
  src_dir: "/c/py/predictive_esp/src/data/resample_data.py"
  CLI_params: "/c/py/predictive_esp/data/interim/train_test/train /c/py/predictive_esp/data/interim/resampled"

merge_by_well:
  src_dir: "/c/py/predictive_esp/src/data/merge_by_well.py"
  CLI_params: "/c/py/predictive_esp/data/interim/resampled/train /c/py/predictive_esp/data/interim/merged_wells"

join_events:
  src_dir: "/c/py/predictive_esp/src/features/join_events.py"
  CLI_params: "/c/py/predictive_esp/data/interim/merged_wells/train /c/py/predictive_esp/data/raw/events /c/py/predictive_esp/data/interim/joined_events"

expand_target:
  src_dir: "/c/py/predictive_esp/src/features/expand_target.py"
  CLI_params: ""

predict:
  SEED: 10
  predictions_name: "predictions.csv"
  src_dir: "/c/py/predictive_esp/src/models/predict.py"
  # input_path output_path model_name
  CLI_params: "/c/py/predictive_esp/data/processed/test.csv /c/py/predictive_esp/data/predictions lr_model.pkl"

train:
  SEED: 10
  src_dir: "/c/py/predictive_esp/src/models/train.py"
  cross_val:
    test_size: 0.3
  # train_path output_path target_name model_name
  CLI_params: "/c/py/predictive_esp/data/processed/train.csv /c/py/predictive_esp/models \"failure_target\" \"lr_model.pkl\""
